name: Upload an Artifact
on:
  push:
    branches: [ gh-pages ]

jobs:
  upload:
    name: Upload an Artifact
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - run: mkdir -p path/to/artifact

    - uses: actions/upload-artifact@v2.2.4
      with:
        name: my-artifact
        path: ./


