name: Upload an Artifact
on:
  push:
    branches: [ gh-pages ]

jobs:
  spelling:
    name: Upload an Artifact
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - run: mkdir -p path/to/artifact

    - run: echo hello > path/to/artifact/world.txt

    - uses: actions/upload-artifact@v2.2.4
      with:
        name: my-artifact
        path: downloads


